version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - apt-get install -y telnet iproute2 net-tools
    - telnet 172.31.89.116 22
  build:
    commands:
      - echo "Done."
