version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - ssh -i /path/my-key-pair.pem my-instance-user-name@my-instance-IPv6-address
      - 
  build:
    commands:
     
      - echo "Done."
